--- #YAML:1.0
name:               Queue-Mmap
version:            0.08
abstract:           Perl extension for shared queue over mmap-ed file
author:
    - Ildar Efremov <iefremov@2reallife.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
